"""empty message

Revision ID: 281b81575038
Revises: 8c00a31b63a4
Create Date: 2025-03-31 10:34:08.907330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '281b81575038'
down_revision = '8c00a31b63a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userProfile',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=True),
    sa.Column('fullName', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('id')
        batch_op.drop_index('username')

    op.drop_table('userprofile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'userProfile', ['signupid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_1', 'userprofile', ['signupid'], ['id'])

    op.create_table('userprofile',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('fullName', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.drop_table('userProfile')
    # ### end Alembic commands ###
