"""empty message

Revision ID: f8b7c565a5fc
Revises: 
Create Date: 2025-08-13 11:12:45.757273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b7c565a5fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('githubUser',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('githubid', sa.Integer(), nullable=True),
    sa.Column('githubAvater', sa.String(length=255), nullable=False),
    sa.Column('githubUsername', sa.String(length=32), nullable=False),
    sa.Column('githubUserEmail', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('githubAvater'),
    sa.UniqueConstraint('githubUserEmail'),
    sa.UniqueConstraint('githubUsername'),
    sa.UniqueConstraint('id')
    )
    op.create_table('userProfile',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=True),
    sa.Column('fullName', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('waitinglist',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('signupid', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['signupid'], ['userProfile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('waitinglist')
    op.drop_table('userProfile')
    op.drop_table('githubUser')
    # ### end Alembic commands ###
